# Guvi Project - 1: Develop automation for User Management Tool by adding a user
# Name : Jeevanand.R
# Course : Software testing


from selenium import webdriver
from selenium.webdriver.common.by import By
import time

class automation_orangehrm:
    driver = webdriver.Firefox()
    
    def automate_newuser(self):
 
        self.driver.get("https://opensource-demo.orangehrmlive.com" )
        time.sleep(5)
        self.driver.maximize_window()
        time.sleep(5)
        username_xpath = self.driver.find_element(by=By.NAME, value="username")
        time.sleep(5)
        password_xpath=self.driver.find_element(by=By.NAME, value="password")
        time.sleep(5)
        login_button_xpath=self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button')
        username_xpath.send_keys("Admin")
        password_xpath.send_keys("admin123")
        time.sleep(5)
        login_button_xpath.click()
        time.sleep(5)
        pim_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a')
        time.sleep(3)
        pim_xpath.click()
        time.sleep(3)
        add_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[1]/button')
        time.sleep(3)
        add_xpath.click()
        time.sleep(3)
        firstname_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[1]/div/div/div[2]/div[1]/div[2]/input')
        firstname_xpath.send_keys("Jeeva")
        time.sleep(3)
        lastname_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[1]/div[1]/div/div/div[2]/div[3]/div[2]/input')
        lastname_xpath.send_keys("raja")
        time.sleep(5)
        save_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]')
        save_xpath.click()
        time.sleep(10)
        admin_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a')
        admin_xpath.click()
        time.sleep(5)
        add_2_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[1]/button')
        time.sleep(5)
        add_2_xpath.click()
        time.sleep(5)
        UserRole_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[1]/div/div[2]/div/div/div[2]/i')
        UserRole_xpath.click()
        time.sleep(5)
        admin_select_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[1]/div/div[2]/div/div[2]/div[2]')
        admin_select_xpath.click()
        time.sleep(5)
        employee_select_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[2]/div/div[2]/div/div/input')
        employee_select_xpath.send_keys("Jeeva raja")
        time.sleep(5)
        employee_select_auto_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[2]/div/div[2]/div/div[2]')
        employee_select_auto_xpath.click()
        time.sleep(5)
        status_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[3]/div/div[2]/div/div/div[2]/i')
        status_xpath.click()
        time.sleep(5)
        status_select_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[3]/div/div[2]/div/div[2]/div[2]')
        status_select_xpath.click()
        time.sleep(5)
        username_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[4]/div/div[2]/input')
        username_xpath.send_keys("Jeevan")
        time.sleep(5)  
        password_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[1]/div/div[2]/input')
        password_xpath.send_keys("Rjeeva@26")
        time.sleep(5)
        confirm_password_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/div[2]/input')
        confirm_password_xpath.send_keys("Rjeeva@26")
        time.sleep(5)
        save_button_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[3]/button[2]')
        save_button_xpath.click()
        time.sleep(10)
        username_2_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/input')
        username_2_xpath.send_keys("Jeevan")
        time.sleep(3)
        UserRole_2_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div/div[2]/i')
        UserRole_2_xpath.click()
        time.sleep(2)
        admin_select_2_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]')
        admin_select_2_xpath.click()
        time.sleep(5)
        employee_select_2_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[3]/div/div[2]/div/div/input')
        employee_select_2_xpath.send_keys("Jeeva raja")
        time.sleep(5)
        employee_select_auto_2_xpath = self.driver.find_element(by=By.XPATH, value='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[3]/div/div[2]/div/div[2]')
        employee_select_auto_2_xpath .click()
        time.sleep(3)
        status_2_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div/div[2]/i')
        status_2_xpath.click()
        time.sleep(5)
        status_select_2_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[4]/div/div[2]/div/div[2]/div[2]')
        status_select_2_xpath.click()
        time.sleep(5)
        search_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[2]/button[2]')
        search_xpath.click()
        time.sleep(5)
        login_out_button_xpath=self.driver.find_element(by=By.XPATH, value="/html/body/div/div[1]/div[1]/header/div[1]/div[2]/ul/li/span")
        login_out_button_xpath.click()
        time.sleep(3)
        login_out_2_button_xpath=self.driver.find_element(by=By.XPATH, value="/html/body/div/div[1]/div[1]/header/div[1]/div[2]/ul/li/ul/li[4]/a")
        login_out_2_button_xpath.click()
        time.sleep(3)
        username_12_xpath = self.driver.find_element(by=By.NAME, value="username")
        password_12_xpath = self.driver.find_element(by=By.NAME, value="password")
        login_12_button_xpath = self.driver.find_element(by=By.XPATH, value='/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button')
        username_12_xpath.send_keys("Jeevan")
        time.sleep(5)
        password_12_xpath.send_keys("Rjeeva@26")
        time.sleep(5)
        login_12_button_xpath.click()
        time.sleep(5)
        

s = automation_orangehrm() 
s.automate_newuser()